# Generated by Django 3.2.4 on 2021-06-14 06:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام برچسب ')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام درس')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام رشته')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام عبارت درسی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.course')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام منبع')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=500, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='متن سوال')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Descriptive'), (1, 'Multi Choice'), (2, 'True False'), (3, 'Blank Fill')], default=0, verbose_name='نوع سوال')),
                ('choice_answer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='متن جواب')),
                ('question_image', models.TextField(blank=True, null=True, verbose_name='تصویر سوال')),
                ('question_voice', models.TextField(blank=True, null=True, verbose_name='فایل صوتی سوال')),
                ('answer_image', models.TextField(blank=True, null=True, verbose_name='تصویر جواب')),
                ('hardness', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='درجه سختی')),
                ('source_etc', models.CharField(blank=True, max_length=150, null=True, verbose_name='منبع غیره')),
                ('number_of_uses', models.IntegerField(default=0, verbose_name='تعداد استفاده')),
                ('number_of_correct_answers', models.IntegerField(default=0, verbose_name='تعداد جواب درست')),
                ('craete_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.category')),
                ('lessons', models.ManyToManyField(to='question_bank.Lesson')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question_bank.source')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پایه ')),
                ('field', models.ForeignKey(default='عمومی', on_delete=django.db.models.deletion.CASCADE, to='question_bank.field')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.grade'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن گزینه')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='question_bank.question')),
            ],
        ),
    ]
