# Generated by Django 3.2.4 on 2021-06-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_alter_question_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lessons',
            field=models.ManyToManyField(to='question_bank.Lesson'),
        ),
    ]
