# Generated by Django 3.2.4 on 2021-06-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_auto_20210612_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='lesson',
            new_name='lessons',
        ),
    ]
