# Generated by Django 3.2.4 on 2021-06-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_rename_lesson_question_lessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='lessons',
            new_name='lesson',
        ),
    ]
