# Generated by Django 3.2.4 on 2021-06-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0004_rename_lessons_question_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='lesson',
            new_name='lessons',
        ),
    ]
